Repository darioielardi/flutter_speed_dial, pull requests merged in 2021-03, with the labels that each got.

#110 Null safety 🔥🔥
  example/pubspec.yaml
  lib/src/animated_child.dart
  lib/src/animated_floating_button.dart
  lib/src/background_overlay.dart
  lib/src/speed_dial.dart
  lib/src/speed_dial_child.dart
  pubspec.yaml
Labels: Ultimate, v3

#118 Possible fix for #117
  lib/src/speed_dial.dart
Labels: Awesome

#129 Added animated color changes feature to main FAB
  lib/src/speed_dial.dart
Labels: enhancement
