Repository darioielardi/flutter_speed_dial, pull requests merged in 2022-10, with the labels that each got.

#272 Add mini parameter
  example/lib/main.dart
  lib/src/animated_floating_button.dart
  lib/src/speed_dial.dart
Labels: Hacktoberfest, Hacktoberfest-accepted

#273 V6.1.0-update
  CHANGELOG.md
  pubspec.yaml
Labels: bug, Hacktoberfest, Hacktoberfest-accepted

#276 Update documentation for SpeedDial and SpeedDialChild
  lib/src/speed_dial.dart
  lib/src/speed_dial_child.dart
Labels: Hacktoberfest, Hacktoberfest-accepted

#278 Bump version to 6.2.0
  CHANGELOG.md
  example/lib/main.dart
  pubspec.yaml
Labels: Awesome, Hacktoberfest-accepted
